KM94 feat(declarativecluster) PART 1: Add reconsilers
oslokommune/okctl pull request #177
Opened 2020-11-27 15:03 UTC by deifyed

## Description

This is the first of several pull requests to implement a declarative way of creating (and later deleting, editing) clusters. 

This part implements a pattern loosely based on Kubernetes controllers. In this PR we define a so called Reconsiler for each resource we want to be able to do CRUD(without the R) operations on. Each reconsiler knows how to create the associated resource based on the information that is available to it. Functionality in following pull requests will handle figuring out which action the reconsiler should do, and how to gather information.

Each reconsiler works on a ResourceNode. Each ResourceNode represents one resource from the cluster. A VPC is a resource. A hosted zone is a resource. Etc.

Godspeed.

2020-11-30 07:52 UTC, ivaruf approved these changes

2020-11-30 14:37 UTC, yngvark requested changes

2020-11-30 14:37 UTC, yngvark commented on pkg/controller/reconsiler/reconsiler.go
> +type ReconsilationResult struct {
Add doc

2020-11-30 14:37 UTC, yngvark commented on pkg/controller/reconsiler/reconsiler.go
> +	Requeue bool
Consider adding doc to this

2020-12-01 07:11 UTC, deifyed commented on pkg/controller/reconsiler/argocd.go
> +func (z *argocdReconsiler) Reconsile(node *resourcetree.ResourceNode) (*ReconsilationResult, error) {
FML

2020-12-01 07:16 UTC, deifyed commented on pkg/controller/reconsiler/argocd.go
> +func (z *argocdReconsiler) Reconsile(node *resourcetree.ResourceNode) (*ReconsilationResult, error) {
I'll rename it after merging all the different parts

2020-12-03 14:04 UTC, merged