Rewrite bugfixes
oslokommune/okctl pull request #463
Opened 2021-04-14 09:55 UTC by deifyed

## Description

- Fixes venv expecting environment argument which is gone
- Adds dash to cluster name validation error message

## Motivation and Context

Due to the pretty huge state rewrite PR, I thought it was a good idea to centralize minor fixes so we don't all fix them 

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have updated the release notes (for the next release).

2021-04-14 10:01 UTC, paulbes approved these changes

2021-04-14 13:37 UTC, yngvark approved these changes

2021-04-14 19:55 UTC, paulbes requested changes
Remember to update nightly.yaml, etc., where we currently use `--config`

2021-04-15 05:47 UTC, deifyed commented
Good catch. Fixed

2021-04-16 06:39 UTC, merged