Km451 remove client identitymanager
oslokommune/okctl pull request #785
Opened 2021-11-25 08:12 UTC by ivaruf

Part of the client/server rewrite

2021-11-29 07:01 UTC, deifyed requested changes

2021-12-03 10:52 UTC, ivaruf commented on pkg/okctl/okctl.go
> +		o.Logger.Errorf("Unable to get certificate cloud provider")
Yes, fixed.

2021-12-03 11:16 UTC, deifyed approved these changes

2021-12-07 11:11 UTC, kmoberg approved these changes

2022-01-06 11:27 UTC, merged