KM478: Support using AWS profile for authentication - WIP
oslokommune/okctl pull request #856
Opened 2022-01-11 14:09 UTC by fredriv

Adds support for using named AWS profiles for authentication, for instance to support AWS Single Sign-On (SSO) based login.

## Description
This patch enables the user to log in using a named AWS profile, specified in the `AWS_PROFILE` environment variable.

Profiles are loaded from the global config and credentials files stored in `~/.aws/` directory, as  opposed to the local config and credentials managed by okctl. The user can use this to authenticate with IAM access keys without setting secrets in environment variables, or to authenticate with profiles using AWS SSO or SAML-based login.

## Motivation and Context

The change is necessary to support the use of AWS SSO for login.

## How to prove the effect of this PR?

Run `okctl` with the `-a aws-profile` parameter to use AWS profile for authentication. Specify the AWS profile to use in the `AWS_PROFILE` environment variable.

## Additional info

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [ ] I have updated the release notes (for the next release).

2022-01-13 12:24 UTC, deifyed approved these changes
I still feel like it should be able to funnel all three different ways of authenticating into one streamlined way of relating to authentication in okctl centralising around profiles, but if it works I guess we could clean it up later

Anyways, good job! Authentication-meddling as the second real PR is what I consider an ilddåp. Looks good

2022-01-13 12:24 UTC, deifyed commented on pkg/credentials/aws/aws.go
> +func NewAuthProfile(region string, getter KeyGetter) Retriever {
What I meant when I suggested implementing this function was to make it do something like:

```go
// pseudo code
func NewAuthProfile(getter KeyGetter) Retriever {
    profile := getter("AWS_PROFILE")

    credentialsFile := ReadAll("well known credentials file path")

    credentials := make(map[string]Credentials)

    err := ini-library.Unmarshal(credentialsFile, &credentials)

    return &AuthStatic { // or other relevant
        Credentials: credentials[profile]
        IsValid: validate(credentials[profile])
    }
}
```

Doesn't that make sense for this use case?

2022-01-13 12:24 UTC, deifyed commented on pkg/credentials/aws/aws.go
> +		AwsProfile:      "default",
This should probably be a constant somewhere. `pkg/config/constant/api.go` is a good place if its needed globally

2022-01-13 14:20 UTC, fredriv commented on pkg/credentials/aws/aws.go
> +		AwsProfile:      "default", // SAML login uses 'default' profile
:+1:

2022-01-13 14:43 UTC, fredriv commented
@deifyed Pushed so changes based on your comments. Thanks! :-)

2022-01-13 17:02 UTC, fredriv commented on pkg/commands/venv_test.go
> +	envVars, err := GetVenvEnvVars(okctlEnv)
Turns out we're calling the `os.UserHomeDir()` function which reads the `$HOME` environment variable, so this didn't work ;-) Instead implemented a helper function `SetOsEnv` in the `testing` package which helps with setting and resetting the environment variables.

2022-01-14 08:41 UTC, yngvark commented on pkg/commands/venv_test.go
> +	envVars, err := GetVenvEnvVars(okctlEnv)
I recommend to pass these values through `opts OkctlEnvironment` (unless it somehow isn't possible). The intention of this struct is to pass all needed data. So the `os` function calls will then be placed in `commands.GetOkctlEnvironment`. 

As a general rule, I also recommend not setting OS environment variables in tests, unless necessary. It has the same issues as settings global variables, hindring tests to be run in parallell, for instance.

2022-01-14 08:45 UTC, yngvark requested changes
Really good research & development! Auth isn't easy.

See my comment on the thread regarding GetVenvEnvVars, I have a suggestion for where to put the `os` function calls.

2022-01-14 14:33 UTC, yngvark approved these changes
Looks good :+1

2022-01-18 06:39 UTC, merged